spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banco_dev
    username: usuario_dev
    password: senha_dev
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: false
cors:
  originPatterns: http://localhost:4200