spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  profile: dev
  hikari:
    minimum-idle: 5
    maximum-pool-size: 10
    idle-timeout: 30000
    connection-timeout: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: PostgreSQLDialect
      jdbc:
        lob: 
          non_contextual_creation: true
  flyway:
    baseline-on-migrate: true