server:
  port: 8889
  compression:
      enabled: true
  servlet:
    context-path: /api
spring:
  application:
    name: dealership
  profiles:
    active: dev
  datasource:
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB
file:
  upload-dir: D:\
api:
  security:
    token:
      secret: i9a(Pj7@39&
spring-doc:
  pathsToMatch: /**
  swagger-ui:
    use-root-path: true
cors:
  originPatterns: http://localhost:8080,http://localhost:8889,http://localhost:80
