server:
  port: 8080
  compression:
      enabled: true
  servlet:
    context-path: /api
#endpoints:
#  enabled: false
#  health:
#    enabled: true
spring:
  application:
    name: dealership
  profiles:
    active: dev
  datasource:
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB
file:
  upload-dir: ${UPLOAD_DIR}
api:
  security:
    token:
      secret: ${JWT_SECRET}
spring-doc:
  pathsToMatch: /**
  swagger-ui:
    use-root-path: true
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:8889
