server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
  servlet:
    context-path: /api

spring:
  application:
    name: dealership
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

api:
  security:
    token:
      secret: ${JWT_SECRET}

springdoc:
  pathsToMatch: /**
  swagger-ui:
    use-root-path: true

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: always

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

cors:
  originPatterns: ${CORS_ORIGINS}