server:
  port: 8080
  compression:
      enabled: true
  servlet:
    context-path: /api
#endpoints:
#  enabled: false
#  health:
#    enabled: true
spring:
  application:
    name: dealership
  profiles:
    active: test
  jpa:
    open-in-view: false
    show-sql: false
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB

file:
  upload-dir: ${UPLOAD_DIR}

api:
  security:
    token:
      secret: ${JWT_SECRET}

