spring:
  datasource:
    url: jdbc:postgresql://ep-jolly-base-a8m96qnx.eastus2.azure.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: moYF5xhW4ujd
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true

cors:
  originPatterns: http://localhost:4200