spring:
  datasource:
    url: jdbc:postgresql://db:5432/dealership_database
    username: postgres
    password: password
  profile: dev
  hikari:
    minimum-idle: 5
    maximum-pool-size: 10
    idle-timeout: 30000
    connection-timeout: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: PostgreSQLDialect
      jdbc:
        lob: 
          non_contextual_creation: true
  flyway:
    url: jdbc:postgresql://db:5432/dealership_database
    user: postgres
    password: password
    baseline-on-migrate: true