spring:
  datasource:
    url: jdbc:postgresql://neondb_owner:moYF5xhW4ujd@ep-jolly-base-a8m96qnx-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: moYF5xhW4ujd
  profile: dev
  hikari:
    minimum-idle: 5
    maximum-pool-size: 10
    idle-timeout: 30000
    connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: PostgreSQLDialect
      jdbc:
        lob: 
          non_contextual_creation: true
  flyway:
    enabled: false